### PR TITLE
changed: change layout to expected python package layout

### PR DESCRIPTION
**Pull request by akva2**
We can thus build a wheel and upload to pypi if wanted. Quick and dirty job, so maybe there's some more cleanup to be done but this works at least.

### CODE REVIEW

**Comment by akva2** [comment]
yes i think it should be ready to go. we can certainly build a wheel now 
```
python3 setup.py sdist bdist_wheel
```
and that should be uploadable to pypi when we deem it appropriate.

**Comment by OPMUSER** [comment]
In it goes, again many thanks for the refactoring.

**Comment by OPMUSER** [comment]
@akva2 I have  question, as I have locally unresolved references.

You changed this import statement:

```
#
# Import OPMRUN Modules
#
from opm_common import (copy_to_clipboard, convert_string, get_time, kill_job, set_gui_options, opm_popup, print_dict,
                        remove_ansii_escape_codes, run_command, tail, wsl_path)
from opm_compress import (change_directory, compress_cmd, compress_files, uncompress_files)
from opm_keyw import keyw_main
from opm_sensitivity import *
from opm_prodsched import *
from opm_wellspec import wellspec_main
from opm_welltraj import welltraj_main
```
to:
```
#
# Import OPMRUN Modules
#
from opmrun import *
```

Which creates the buch of unresolved references. Is this because you are using Python 3.8 and I'm using 3.7, or is there something else amiss at my end.

**Comment by akva2** [comment]
Imports are done in __init__.py. i suggest using pip3 install . --user --editable. You cannot run opmrun.py directly.

**Comment by OPMUSER** [comment]
But Pycharm complains about the unresolved references and will not run opmrun (like you said), so how do I get to fix the unresolved references and be able to run from within PyCharm IDE?

And how to now run the program. Previously, I just called the Python opmrun.py  

 `pip3 install . --user --editable`

So this installs opmrun, correct?

Sorry for the dumb questions.

**Comment by akva2** [comment]
no worries, everything has to be learned.

opmrun is now a python module with an entry point defined in setup.py
```
    entry_points={
        'gui_scripts': [
            'opmrun=opmrun.opmrun:main'
        ],
    },
```

this basically creates a wrapper script in the bin folder that basically executes __init__.py, then runs the given method.
thus, you run it as 'opmrun'.

pip3 install --editable  . installs the python module (execute this in top of tree) in such a way that the installation points to your source tree. that way you don't have to execute install for every change you make (note: i screwed up the order of params in first post, the . needs to go after --editable)

--user installs to user folder instead of system wide.

hope this helps.

**Comment by OPMUSER** [comment]
@akva2 This did not work for me.

I changed directory to the top directory, where setup.py is located, and ran:
`
pip3 install --editable  .`

I got the following errors:

```
Microsoft Windows [Version 10.0.19043.2364]
(c) Microsoft Corporation. All rights reserved.

D:\User\XXXXXX\Development\GitHub\opm-utilities\opmrun>pip3 install --editable  .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///D:/User/XXXXXX/Development/GitHub/opm-utilities/opmrun
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\User\\XXXXXX\\Development\\GitHub\\opm-utilities\\opmrun\\setup.py'"'"'; __file__='"'"'D:\\User\\XXXXXX\\Development\\GitHub\\opm-utilities\\opmrun\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\BAXEND~1\AppData\Local\Temp\pip-pip-egg-info-xtbh3skb'
         cwd: D:\User\XXXXXX\Development\GitHub\opm-utilities\opmrun\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\User\XXXXXX\Development\GitHub\opm-utilities\opmrun\setup.py", line 5, in <module>
        long_description = fh.read()
      File "c:\program files\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1041: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding file:///D:/User/XXXXXX/Development/GitHub/opm-utilities/opmrun. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Looks like it is coding, but I don't know how to fix this.

Help very much appreciated.

**Comment by akva2** [comment]
try
```
with open("DESCRIPTION.md", "r", encoding='utf-8') as fh:
    long_description = fh.read()
```
in setup.py, ie specify that it's utf-8.

**Comment by OPMUSER** [comment]
@akva2 Many thanks, that worked. So where was it installed and how do I run it - nearly there.

**Comment by akva2** [comment]
uhm you didn't give --user so i guess it installed to c:/users/default or whatever that one is called. it should be in your path, you run with the 'opmrun' command.

**Comment by OPMUSER** [comment]
Okay, found it and appears to working fine under Windows. Also got it running under Linux using git to get a sparse clone, and then installing. Just a minor error on startup not finding an icon, I'll take a look at that later. 

Just need to figure how to do the Windows clone and install via Pycharm and then I'm done.

I just want to say thank you again, for the refactoring, I spent many hours trying to do this as there is lots of conflicting and dated information on the web describing how to do this, but in the end it was relatively straight forward. So thank you.

**Pull request merged**
