### PR TITLE
add boost path to LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by akva2**
... but i forgot to push this.

### CODE REVIEW

**Comment by akva2** [comment]
actually, i found a better way.

**Comment by alfbr** [comment]
Just a comment, feel free to ignore. I believe you do not need LD_LIBRARY_PATH, at least we have never used it, and Boost links fine out-of-tree. Using LD_LIBRARY_PATH is dangerous since it overrides system locations, so it may break other applications.

**Comment by akva2** [comment]
i will ignore - sort of. you should know that i know what i'm doing ;)

we are running an application which uses a boost that is now provided from a scl. these are not in default linker paths. i wanted to do it this way to put a little less load on the user invoking the container, but i ended up doing it the expected way by using the scl utility in the jenkins invocation.

**Comment by alfbr** [comment]
> you should know that i know what i'm doing ;)

Indeed, like a goldfish I just need the occasional reminder :-)

**Pull request closed without merging**
