### PR TITLE
OPMRUN 2019-04-1

### PR DESCRIPTION
**Pull request by OPMUSER**
OPMRUN updated to 2019-04-1 version with additional functionality and bug fixes. Documentation and program documentation updated. Program documentation also explains how to create a binary executable that will run on all Linux boxes. Binary executable also included in this release.

See the Release Notes and the source code for further information.

### CODE REVIEW

**Comment by OPMUSER** [comment]
Atgeirr,

I just sent a PR for a update to OPMRUN. Unfortunately, I was leaning how to use GitHub Desktop for Linux at the time so the PR looks a bit confusing, so  please accept my apologies. Locally I put all my changes in a separate branch 2019-04-1, but I'm not sure how that translates on GitHub. This should be a new main release for OPMRUN.

There should be the following files updates.

**OPMRUN**
Binary executable, should be part of the update. One does not need Python or any dependencies for this to work. The source code documents how the binary executable was generated.
**OPMRUN Introduction.pdf**
Presentation outlining the features of OPMRUN.
**opmru.py**
Source code, major re-factoring of source code. I have also added additional documentation, including release history and how to generate an executable.
**README.md**
Stand README file
**Release-Notes**
Release notes, basically copied from opmru.py.

Also I have documented this version in the 2019-04 release of the OPM Flow manual.

Again apologizes for the confusion.

**Comment by atgeirr** [comment]
This should be all good, except perhaps for the inclusion of the compiled binary, maybe that should be packaged properly instead? @akva2 what do you think?

**Comment by akva2** [comment]
Binaries are in general not wanted in source control systems so if it was up to me it is a blocker.

**Comment by OPMUSER** [comment]
How do I package the binary? The issue with Python is that everybody is using different versions of Python and then we have different version of the modules, so it is not straight forward for engineers to build. With the binary there is no need to install Python at all. 

So I am open to suggestions on how we can distribute this because it will make running OPM Flow  very easy for the engineers, especially for those with limited Linux experience. My original intention was, hopefully to be part of the OPM Flow package, but I would like some feedback first before I/we go down that route.

**Comment by joakim-hove** [comment]
> The issue with Python is that everybody is using different versions of Python and then we have different version of the modules, so it is not straight forward for engineers to build. With the binary there is no need to install Python at all.

It have had the plan coming with more feedback on this; will try harder this afternoon. My short comment is that although the use of a binary - and no subsequent need to install Python - seems appealing at first I think that is deceiving, binary compatibility is even more challenging.

I think the really short answer is that you need to decide on a Python version to support, right now you are targeting Python 3.6 which is really quite close to the screaming latest and greatest - general reservoir engineers will typically not have access to such a new version. Then I would suggest going with standard Python installation/packaging - i.e. `setup.py` - it is not very elegant, but it is the standard Python way.

I'll try to give you more feedback later today.

**Comment by joakim-hove** [comment]
Hello David; I have looked a bit more through the opmrun script today. I have two suggestions:

1. As I already mentioned I *really* think you should use the normal `setup.py` based installation, instead of `pyinstaller` - for one thing you avoid the need to embed the binary in the source code, but more importantly you are more certain that things will just work. My experience with `pyinstaller` and similar tools is that they are a bit fragile. `setup.py` is not a very comfortable tool, but you have a quite simple - pure Python project and then `setup.py` does the job.

2. You have made quite extensive use of the `Path` class from the `pathlib` module; the `pathlib` module came in python version 3.4. I *think* the use of `Path/pathlib` is the most serious obstacle to Python2.7 compatability (which is unfortunately still quite relevant). If I were you I would avoid using `Path/pathlib` - if you are interested I can implement a small `Path` class for you - which will give you everything *except* the `/` operator - that must be performed with `os.path.join( ... )`.

**Comment by joakim-hove** [comment]
Here is an untested `Path` class:
```Python
import glob
import os
import os.path

class Path(object):

    def __init__(self, arg_path):
        self.path = arg_path
        self.name = os.path.basename(arg_path)
        self.stem, _ = os.path.splitext(self.name)

        self.parents = []
        tmp_path = arg_path
        while True:
            path, entry = os.path.split(tmp_path)
            // This stop condition is probably too naive ...
            if path in ["/", ""]:
                break

            self.parents.append(path)
            tmp_path = path


    def with_suffix(self, new_ext):
        base, _ = os.path.splitext(self.path)
        return "{}.{}".format(base, new_ext)


    def glob(self, pattern):
        return glob.glob(os.path.join(self.path, pattern))


    def __str__(self):
        return str(self.path)
```

**Comment by OPMUSER** [comment]
And there I was thinking, I was done .

I'll take a look at this and see what can be done as it will entail some changes.

**Comment by OPMUSER** [comment]
Atgeirr,

I just sent a PR for a update to OPMRUN. Unfortunately, I was leaning how to use GitHub Desktop for Linux at the time so the PR looks a bit confusing, so  please accept my apologies. Locally I put all my changes in a separate branch 2019-04-1, but I'm not sure how that translates on GitHub. This should be a new main release for OPMRUN.

There should be the following files updates.

**OPMRUN**
Binary executable, should be part of the update. One does not need Python or any dependencies for this to work. The source code documents how the binary executable was generated.
**OPMRUN Introduction.pdf**
Presentation outlining the features of OPMRUN.
**opmru.py**
Source code, major re-factoring of source code. I have also added additional documentation, including release history and how to generate an executable.
**README.md**
Stand README file
**Release-Notes**
Release notes, basically copied from opmru.py.

Also I have documented this version in the 2019-04 release of the OPM Flow manual.

Again apologizes for the confusion.

**Comment by OPMUSER** [comment]
I'll re-open this on a separate branch so it is clean update.

**Pull request closed without merging**
