### PR TITLE
OPMRUN Template Updates

### PR DESCRIPTION
**Pull request by OPMUSER**
Update OPMRUN Velocity Templates mostly comments and formatting, plus new keywords.
HEADER and GLOBAL sections

### CODE REVIEW

**Comment by OPMUSER** [comment]
Ready for review

**Comment by blattms** [comment]
Large PR (with mostly minimal changes, a la Data/Ubuntu version). Would help if you would point out relevant changes/commits

**Comment by OPMUSER** [comment]
List of major changes:

1. RUNSSPEC section: Added  GRIDOPTS, BPARA, and MINNPCOL, minor changes NETWORK, NUPCOL, PARALLEL.
2. GRID section: Removed GRIDOPTS. Added HXFIN, HYFIN, NXFIN, NYFIN, NZFIN, PERMTHT, minor edits to MULTX/Y/Z etc.,
3. EDIT section: Only comments changed.
4. PROPS section:  Updated MICPPARA, added SGOFLET, SWGFLET, and SWOFLET, Note the SGOF and SLGOF keywords got reversed with the current PR, will issue a correction.
5. REGION section: added FIP template.
6. SOLUTION section: Corrected AQUFET, and SOLUTION.velocity, added RS, RVW, SALT, and SALTP.
7. SUMMARY section: Updated SUMMARY.vm to include more thermal vectors.
8. SCHEDULE section: LIFTOPT, WCONINJE, WTMULT, WVFPEXP minor edits,  added RESTART template.
9. DATA example templates - just comments changed.
10. HEADER section: minor edit DEBUG. Note HEADER-LICENSE is incorrect, in this PR will issue a correction.
11. MODEL example templates - just comments changed.
12. USER example templates - just comments changed.

Note I use the templates with my editor and for the manual examples, so I try to keep everything consistent, but sometimes errors creep in.

**Comment by OPMUSER** [comment]
All corrections done.

**Pull request merged**
