### PR TITLE
Additional Velocity Templates (PVTSOL and MICP etc)

### PR DESCRIPTION
**Pull request by OPMUSER**
Additional Velocity Templates (PVTSOL and MICP etc) to be consistent with manual.

### CODE REVIEW

**Comment by blattms** [comment]
Any reason not to merge?

**Comment by OPMUSER** [comment]
No - I just forgot about it, it was so long ago.

**Comment by OPMUSER** [comment]
Merge?

**Comment by bska** [comment]
Is there a requirement that `.vm` files not end in a newline character?

**Comment by OPMUSER** [comment]
Using the example below:
image
If there was a newline  character, and thus line number 36, it would mean that there was an extra blank line in the input deck when the template was invoked.

I have tried to avoid the extra blank line, but I have not necessarily been consistent with this.

**Comment by bska** [comment]
> If there was a newline character, and thus line number 36, it would mean that there was an extra blank line in the input deck when the template was invoked.

A final, end-of-file, newline character does not add an end-of-file blank line.  We're talking about the difference between the Python statements
```python
print('hello', end='')
```
and
```python
print('hello')
```
If we're **really** picky about semantics, the current `.vm` files technically aren't text files because of the missing `\n` on the last line.

**Pull request merged**
